version: '3'

services:
  app-nodb:
    container_name: stac-fastapi-nodb
    image: stac-utils/stac-fastapi-nodb
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8083
      - RELOAD=false
      - ENVIRONMENT=local
      - WEB_CONCURRENCY=10
      - 38_PORT=9851
      - 38_HOST=172.17.0.1
    ports:
      - "8083:8083"
    volumes:
      - ./stac_fastapi:/app/stac_fastapi
      - ./scripts:/app/scripts
    depends_on:
      - tile38
    command:
      bash -c "./scripts/wait-for-it-es.sh tile38:9851 && python -m stac_fastapi.nodb.app"

  tile38:
    image: "tile38/tile38"
    ports:
     - "9851:9851"

networks:
  default:
    name: stac-fastapi-nodb-network
